apiVersion: v1
kind: Service
metadata:
  name: cve-search-engine-service
  namespace: vector
  labels:
    app: cve-chatbot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
  selector:
    app: cve-chatbot