apiVersion: v1
kind: Service
metadata:
  name: cve-chatbot-deployment
  labels:
    app: cve-chatbot
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cveSearchEngineService.type }}
  selector:
    app: cve-chatbot
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.cveSearchEngineService.ports | nindent 6 }}
