apiVersion: v1
kind: Service
metadata:
  name: cve-search-engine-service
  labels:
    app: cve-chatbot
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: chatbot.missionk8s.xyz
spec:
  type: ClusterIP
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: cve-chatbot