apiVersion: v1
kind: Service
metadata:
  name: cve-search-engine-service
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: chatbot.missionk8s.xyz
  labels:
    app: cve-chatbot
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cveSearchEngineService.type }}
  selector:
    app: cve-chatbot
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.cveSearchEngineService.ports | nindent 6 }}
