apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  api_key: {{ .Values.openaiApiKey.apiKey | b64enc | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson | quote }}
